### ISSUE TITLE
MF: Front coilgun can shoot out canopy

### ISSUE THREAD

**Issue by paullessing** [limehouselabs/good-ship-faff#19]
I am reporting a:
```
[x] Unintended feature
```

The permitted angle on the front coilgun allows shooting out the captain's bridge ceiling.

The permitted angle on the rear coilgun allows sinking the ship via perforations to the engine room.

**Comment by Lexicality** [comment]
Fixed in 27dbd4bcc80187277f1ae5b8c020f50c0643f478
